[
    "https://github.com/intendantio/intendant-tuya-smartobject",
    "https://github.com/intendantio/intendant-netatmo-home-coach-smartobject",
    "https://github.com/intendantio/intendant-lametric-time-smartobject",
    "https://github.com/intendantio/intendant-hue-switch-smartobject",
    "https://github.com/intendantio/intendant-hue-light-smartobject",
    "https://github.com/intendantio/intendant-hue-hub-smartobject",
    "https://github.com/intendantio/intendant-hue-plug-smartobject"
]