"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var _default=(a,b)=>{//Get all widget
//Get one widget
//Insert widget
//Update widget
//Delete widget
//Insert source in widget
//Delete source in widget
//Insert content in widget
//Delete content in widget
a.get("/api/widgets",async(a,c)=>{a.url="/widgets";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.getAll())}),a.get("/api/widgets/:idWidget",async(a,c)=>{a.url="/widgets/:idWidget";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.getOne(a.params.idWidget))}),a.post("/api/widgets",async(a,c)=>{a.url="/widgets";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.insert(a.body.reference,a.body.icon,a.body.contents,a.body.sources))}),a.put("/api/widgets/:idWidget",async(a,c)=>{a.url="/widgets/:idWidget";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.update(a.params.idWidget,a.body.content))}),a.delete("/api/widgets/:idWidget",async(a,c)=>{a.url="/widgets/:idWidget";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.delete(a.params.idWidget))}),a.post("/api/widgets/:idWidget/sources",async(a,c)=>{a.url="/widgets/:idWidget/sources";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.insertSource(a.params.idWidget,a.body.reference,a.body.source,a.body.action,a.body.arguments))}),a.delete("/api/widgets/:idWidget/sources/:idSource",async(a,c)=>{a.url="/widgets/:idWidget/sources/:idSource";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.deleteSource(a.params.idWidget,a.params.idSource))}),a.post("/api/widgets/:idWidget/contents",async(a,c)=>{a.url="/widgets/:idWidget/content";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.insertContent(a.params.idWidget,a.body.type,a.body.content))}),a.delete("/api/widgets/:idWidget/contents/:idContent",async(a,c)=>{a.url="/widgets/:idWidget/content/:idContent";let d=await b.controller.authentification.checkAuthorization(a);d.error?c.send(d):c.send(await b.controller.widget.deleteContent(a.params.idWidget,a.params.idContent))})};exports.default=_default,module.exports=exports.default;